# ตัวอย่างไฟล์ monitoring/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'p9s_chatbot'
    metrics_path: /metrics
    static_configs:
      - targets: ['<Pi_IP>:8000']
