version: '3.8'

services:
  p9s_chatbot:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:///data/main.db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      FB_PAGE_ACCESS_TOKEN: ${FB_PAGE_ACCESS_TOKEN}
      FB_VERIFY_TOKEN: ${FB_VERIFY_TOKEN}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD_HASH: ${ADMIN_PASSWORD_HASH}
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    command: >
      gunicorn app:app
        --bind 0.0.0.0:8000
        --workers 2
        --threads 4
        --worker-class uvicorn.workers.UvicornWorker
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
